### ISSUE TITLE
Hardware Serial

### ISSUE THREAD

**Issue by torchris** [bportaluri/WiFiEsp#12]
Sorry if this is an obvious question. I'm going to try this library on an Arduino Mega 2560 and I would like to understand how to use the hardware serial ports.  Should I just comment out the SoftWareSerial info and in Setup just go to "Serial1.begin(9600);"? If so, then I am also assuming you can just use any of the Mega UARTs (Serial1, Serial2, Serial3)?

**Comment by WheresWally** [comment]
Yep... now that a stream cab be passed to the init(). 
Make sure you have the latest version.

**Comment by bportaluri** [comment]
Look at the examples.
There is always a short ifndef at the beginning.
```
// Emulate Serial1 on pins 6/7 if not present
#ifndef HAVE_HWSERIAL1
#include "SoftwareSerial.h"
SoftwareSerial Serial1(6, 7); // RX, TX
#endif
```
This will emulate the Serial1 interface on boards like Arduino Uno. On Arduino Mega Serial1 is available and this code will be skipped. Doing so, Seriaal1 is always defined so you can pass it to the init method.
```
WiFi.init(&Serial1);
```
When using an emulated serial, the ESP's RXD/TXD pins must be connected to pins 6/7.
When using an hardware serial, the ESP's RXD/TXD pins must be connected to pins TX1/RX1.
On Arduino Mega you can use Serial2 and Serial3 as well and higher baud rates.

**Comment by torchris** [comment]
Perfect, thanks!

**Comment by vijaynidhani** [comment]
Perfact, was looking for similar solution, i was trying to connect GPS serial and ESP01 with Mega, this will probably work for me as well. Thanks.

**Comment by caosytrung** [comment]
anybody can tell me the result with Mega? please. I try on Arduino Mega 2560 with Hardware Serial1. Serial1 work perfect on AT command but got same the same result T_T( sorry for my English)

**Comment by jandrassy** [comment]
@caosytrung, what result? there is no problem with Mega. this was only a question and an explanation about use of Serial1

**Comment by tagsensor** [comment]
Eu também tive problema para fazer funcionar a biblioteca no placa Arduino mega. Se o que foi feito.
Comente:
// Emulate Serial1 on pins 6/7 if not present
//#ifndef HAVE_HWSERIAL1
//#include "SoftwareSerial.h"
//SoftwareSerial Serial1(10, 11); // Pino TX no 10, Pino RX no 11
//#endif

Substitua Serial1 por Serial2:
Serial2.begin(9600);
WiFi.init(&Serial2);

pinos TX da ESP no pino 17 (RX2) e o RX da ESP no pino 16 (TX2)

**Comment by jandrassy** [comment]
@tagsensor, try Serial2.begin(115200);
