### ISSUE TITLE
Connection Bug: client.connected() says CONNECTED but it isnt connected no more

### ISSUE THREAD

**Issue by WheresWally** [bportaluri/WiFiEsp#14]
After GETting a block of data back, the client.connected() remains true, even though the connection is now closed.
seems like _sock isnt being set to 255 when the end tag "CLOSED" is received.

Doing a GET manually, this is how V1.5 ends the connection with a connection number,CLOSED.
</html>4,CLOSED

...
</html>.
client.connected() says CONNECTED
> getConnectionStatus
----------------------------------------------
>> AT+CIPSTATUS
STATUS:4

OK
---------------------------------------------- > 4

**Comment by bportaluri** [comment]
Can you please download the latest library from GitHub and test it?
https://github.com/bportaluri/WiFiEsp
I have improved the connection handling. If it works fine for you I will publish it.

**Comment by WheresWally** [comment]
Yes that worked very nicely, thanks.



Data packet 0 95
0,CLOSED

Connection closed
.
client.connected() says NOT CONNECTED
> getConnectionStatus
----------------------------------------------
>> AT+CIPSTATUS
STATUS:4

OK
---------------------------------------------- > 4

Terminal Mode Forever
