### ISSUE TITLE
Working great with Mega but not working with Uno,Pro Mini

### ISSUE THREAD

**Issue by khawajamechatronics** [bportaluri/WiFiEsp#140]
Hi,

I am having issue getting it work on Pro mini, 

Can any one confirm its working with Uno or Pro mini?

It gives garbage values on Serial when I set Debug Level 4

**Comment by Erwarrior** [comment]
yes it is working fine on UNO. I have assigned the softwareserial to it and hardware serial for the debugging.

**Comment by khawajamechatronics** [comment]
What baud rate are you using For debug Serial and Software Serial?
