### ISSUE TITLE
How to connect to the open network? Which only having SSID but no password?

### ISSUE THREAD

**Issue by Erwarrior** [bportaluri/WiFiEsp#143]
I am trying to connect to the open network. i have used the WiFi.beginAP("ssid"); showing connected but  not getting any IP. Please help. Did anyone tried to get connected with the open network.

**Comment by jandrassy** [comment]
why beginAP()? it start the esp8266 as access point, not joins access point

**Comment by Erwarrior** [comment]
yup this is wrong, not the way. Actually there is no function which can only pass the ssid and get connected to open network. How to do this.

**Comment by jandrassy** [comment]
try begin with some dummy password

**Comment by Erwarrior** [comment]
hey i have open network in my campus and there is no password.  so dummy password i dont think will work.
Anyway i am now digging into the library to write the function for connecting to open network.

**Comment by Tweeks-va** [comment]
I just did it. Just make
`char pass[] = ""; `
 
Tweeks
