### ISSUE TITLE
Use Hardware *Serial* (not HW Serial1 or SoftSerial)? 

### ISSUE THREAD

**Issue by alastaira** [bportaluri/WiFiEsp#163]
Firstly, thanks very much for this library - it's saves me a great deal of time already compared to manually writing AT+ commands :) 
Like many other people it seems, I'm now trying to use ESP-01 + PubSubClient as a cheap and easy way to control/monitor an Uno/Nano via MQTT.  After originally trying various baud rates with SoftwareSerial, I then upgraded to AltSoftSerial and found that fixed many of the original problems regarding garbage characters and dropouts. However, I still find that I get disconnected frequently, using any combination of baud rates between 9600 and 114200 (and this seems specific to when using WiFiEsp with the PubSubClient - when issuing AT+ commands via SoftSerial I don't experience the same problem), and also messages in subscribed topics don't always get noticed (although publishing works fine)
It seems related to some bottleneck or limitation in the software serial connection, and so it occurs to me, that there should be an option to setup WiFiEsp to use the dedicated hardware Serial on an Uno? e.g. 

  Serial.begin(115200);
  // Initialize ESP Wi-Fi using the hardware serial
  WiFi.init(&Serial);

Sure, this would preclude the use of the serial connection for any USB debugging information, and you have to disconnect the ESP-01 each time you want to upload and new code, but in terms of offering a reliable connection for a production device it would seem to be the best option. There are other libraries that use the HW Serial pins for timing-critical functions (e.g. a MIDI interface) when SoftwareSerial emulation is not good enough, but I couldn't get it to work with WiFiEsp.

Should this be possible? If so, are there any additional steps required that I'm missing? It appears that the library assumes "Serial" will always only used for debugging information (e.g. in use of Serial.print in the LOGINFO function) - is it that noise which prevents it from being used as the the interface itself?

Thanks,

**Comment by jandrassy** [comment]
src/utility/debug.h
#define _ESPLOGLEVEL_ 0
