### ISSUE TITLE
Busy p

### ISSUE THREAD

**Issue by WheresWally** [bportaluri/WiFiEsp#17]
i was wondering why the IP address is all 0.0.0.0
ever come across this?

---------------------
>> AT+RST

---------------------

busy p...

OK
WIFI DISCONNECT
ü˜Lü•þ€=)�œ€=)ÿ€=�†Ü
ready
WIFI CONNECTED
WIFI GOT IP
---------------------
>> AT+CIPAP_CUR?

---------------------
AT+CIPAP_CUR?

busy p...
+CIPAP_CUR:ip:"0.0.0.0"
+CIPAP_CUR:gateway:"0.0.0.0"
+CIPAP_CUR:netmask:"0.0.0.0"

OK

**Comment by bportaluri** [comment]
Are you using the library or sending AT commands?
Have you tried to enable the DHCP?
AT+CWDHCP=1,1 for station
AT+CWDHCP=0,1 for AP

I think the second one is missing in the EspDrv.wifiStartAP method

**Comment by bportaluri** [comment]
I have added "AT+CWDHCP_CUR=0,1" command in EspDrv.wifiStartAP method
https://github.com/bportaluri/WiFiEsp/commit/618426d2997a0c8c00bbb801e61ecb139dcc9e0d

**Comment by WheresWally** [comment]
when I use the library it does show the IP address assigned.

however if I reprogram the Arduino with the Terminal program that just acts as the medium, then it does show the above symptoms.


```
[WiFiEsp] Initializing ESP module
[WiFiEsp] Initilization successful - 1.5.0
Wifi status=3
Attempting to connect to SSID: nilfilum
[WiFiEsp] Connected to nilfilum
Connected to wifi
SSID: nilfilum
IP Address: 192.168.0.32
signal strength (RSSI):-67 dBm

**Comment by WheresWally** [comment]
Doesnt show up now, seems to be a timing thing of when commands at sent.
