### ISSUE TITLE
HTTPClient.h 

### ISSUE THREAD

**Issue by aster94** [bportaluri/WiFiEsp#174]
Ciao Bruno!
What about supporting the auto formattation of requests like esp32 and esp8266 do?
https://github.com/espressif/arduino-esp32/tree/master/libraries/HTTPClient
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266HTTPClient

**Comment by jandrassy** [comment]
use the ArduinoHttpClient library

**Comment by aster94** [comment]
thanks, I will use it, I will leave the issue open because I think that all inside one library would be better

**Comment by jandrassy** [comment]
> thanks, I will use it, I will leave the issue open because I think that all inside one library would be better

using the base class Client implemented by all standard Arduino networking libraries the HttpClient is universal and doesn't need to have a copy in every library

**Comment by aster94** [comment]
> > thanks, I will use it, I will leave the issue open because I think that all inside one library would be better
> 
> using the base class Client implemented by all standard Arduino networking libraries the HttpClient is universal and doesn't need to have a copy in every library

I realized this only now, you are right I am closing!
