### ISSUE TITLE
Can connect but DHCP not working

### ISSUE THREAD

**Issue by c3101** [bportaluri/WiFiEsp#187]
Using the ConnectWPA example script, on an arduino uno, with a esp8266 module, it reports to the serial monitor that it is connected.

I can verify that from my Ubiquiti Wifi manager, and can see that the AP has allocated an IP via dhpc.

But the serial monitor never shows the IP address, and I cannot connect to anything from the esp8266:

SSID: XXXX
[WiFiEsp] >>> TIMEOUT >>>
BSSID: B4:FB:E4:DA:32:E1
Signal strength (RSSI): -75
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] No tag found
IP Address: 0.0.0.0
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] No tag found
MAC address: 00:00:00:00:00:00

WifiEsp ver 2.2.2

**Comment by JAndrassy** [comment]
hardware Serial or SoftwareSerial? baud rate? AT firmware version?

it is not a DHCP problem. MAC address is not assigned by DHCP. the library didn't catch the response from esp8266

**Comment by c3101** [comment]
Software Serial
Baud 115200

AT+GMR
AT version:1.2.0.0(Jul  1 2017 20:04:45)
SDK version:1.5.4.1(39cb9a32)
Wireless-Tag Technology Ltd.

Doing AT+CWJAP="XXXX","mystupidpassword" works, so the library must be missing something somewhere

**Comment by JAndrassy** [comment]
SoftwareSerial can't read reliably at 115200 baud. and this library too. use 9600 baud

**Comment by c3101** [comment]
When using 9600, the library says there is no wifi module, and doesn't try to even connect

**Comment by JAndrassy** [comment]
> When using 9600, the library says there is no wifi module, and doesn't try to even connect

because you must set the baud rate in AT firmware too

**Comment by c3101** [comment]
OK, then I'm out of my depth. Can you please help with some documentation on how to do that?

**Comment by JAndrassy** [comment]
AT+UART_DEF=9600,8,1,0,0

**Comment by c3101** [comment]
Thanks so much, will try tonight! :)

**Comment by c3101** [comment]
Awesome, works a treat! Thanks so much for all the help.

**Comment by lewixlabs** [comment]
> SoftwareSerial can't read reliably at 115200 baud. and this library too. use 9600 baud

I confirm, with 9600 speed, module correctly connects in WiFi
