### ISSUE TITLE
scan network and encryption type

### ISSUE THREAD

**Issue by ricmail85** [bportaluri/WiFiEsp#19]
Hi,

Thanks for your very good job with this library. I have a question about implementing the scannetwork function in order to see available APs around. 

In this case the command is AT+CWLAP and, as reported in https://room-15.github.io/blog/2015/03/26/esp8266-at-command-reference/ the first number gives you the encryption type too.

Do you think to implement the possibility to see near aps around? With the iteadlib this function is implemented, resulting in an output string. Is it possible to do the same with your lib?

Thanks again.
Bye

**Comment by bportaluri** [comment]
I have implemented the scanNetworks() method in release 1.5.
As always, is works like the original Arduino WiFi library.
See example: https://github.com/bportaluri/WiFiEsp/blob/master/examples/ScanNetworks/ScanNetworks.ino
