### ISSUE TITLE
favicon.ico fails - multiple connections not supported well?

### ISSUE THREAD

**Issue by joysfera** [bportaluri/WiFiEsp#2]
With 'wget' calling the webserver repeatedly it seems to work well but if I use Google Chrome that asks for both index.html and favicon.ico at the same time it fails and reads some garbage, then timeouts:

This is correct, connection ID = 0:

    ConnID: 0
    Bytes: 356
    returning client 0
    new client
    GET / HTTP/1.1
    Host: 192.168.105.160
    Connection: keep-alive
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
    DNT: 1
    Accept-Encoding: gzip, deflate, sdch
    Accept-Language: cs,en-US;q=0.8,en;q=0.6

And this is the failing connection:

    +IPD,1,330:GET /favicon.ico HTTP/1.1
    Host: 192.168.105.160
    Connection: keep-alive
    User-Agent:ola.(1 nx86 lWK/76(T,leek rm40213Sa/76Aet*
    D:
    Rer t/1.81.0
    etndggi fa,dhAetaug ,-S=8eq.
    O

    TIMEOUT >>>

**Comment by bportaluri** [comment]
Hi Peter,
thank you for your interest in WiFiEsp.
I know about this issue. It is not very easy to deal with AT commands through serial but I think this can be fixed.
I'm currently working on another important rework. I'm making the WiFi object static as in the original WiFi library to improve compatibility with existing Arduino sketches based on WiFi and Ethernet libraries.
Stay tuned

**Comment by joysfera** [comment]
Well, I think the +IPD was simply not expected thus not handled. I believe that you need to search for the ESC sequence starting with '+' in incoming data and then parse out the IPD and recognize a new connection is coming. Currently it is just echoed from input to output like an ordinary data. Somewhere the +IPD check is missing, not exactly sure where, I am not familiar with the code yet.

**Comment by joysfera** [comment]
Bruno, I have found the following pretty insightful discussion with possible suggestions for "mixed data streams": https://github.com/Diaoul/arduino-ESP8266/issues/15 and https://github.com/Diaoul/arduino-ESP8266/pull/14
Maybe you can get inspired there, too.

**Comment by bportaluri** [comment]
Hi Petr,
can you please try the latest version it should better handle multiple client connections.
There are still some problems but they seems to be related to ESP serial buffer and not to my library.
I'm still trying to understand where the problems are.
I'm also planning to move to the new AT firmware. What ESP firmware version are you using?

**Comment by joysfera** [comment]
I have just tested the latest github source and I can't see any improvement. The Chrome asking for favicon.ico is still not handled correctly - the +IPD is printed as an output text instead of being parsed and subsequent data handled as a new connection. Second connection (say from a different browser) causes the first one to time out and die so it's highly unstable in this regard.
For reference, I use SoftwareSerial and the firmware is 0018000902-AI03. I am not exactly into upgrading the firmware because I heard that the newer one (0022xxxx) has worse WiFi stability and some crucial command is broken.
This guy ("taoyuan") forked "arduino-ESP8266" here on github and implemented something that looks like a working approach to handle the +IPD in incoming data stream. Please check this out: https://github.com/taoyuan/arduino-ESP8266/commit/ac5372cd4a9b7c2f9eb0468d93ae5d99dd2cb2f7
However, neither his version passes the Chrome "test" (two concurrent connections) on my setup.
I am wondering if it is possible to handle it at all using the AT commands set.

**Comment by joysfera** [comment]
Bruno, this is important: I have just increased SoftwareSerial's buffer size from 64 to 254 bytes and things are much better now! The +IPD is correctly handled now, it seems! At least Google Chrome requesting "/" and "/favicon.ico" at the same time no longer causes issues. Great work.

However, visiting the web server from second client (no matter if from localhost or a different machine) causes the first one to lose connection and bad things happen - like for example the web page on the first client contains AT commands "AT+CIPCLOSE=0". This is something I don't quite understand. Is it another issue caused by SoftwareSerial library? Or is it a shortcoming of the ESP8266 AT command set? Or its serial buffer?

**Comment by bportaluri** [comment]
I have released a new release working with the new firmware.
Can you give it a try?
I think the multiple connections problem is still present.
I will open another issue on GitHub to track it.
