### ISSUE TITLE
Arduino nano Every compiling error

### ISSUE THREAD

**Issue by athdimitriou** [bportaluri/WiFiEsp#205]
Hi all,

I am having issues compiling the library on Arduino nano Every. I have tried to #include <WiFiEsp.h> to a bare minimum to minimise potential issues and still I am getting Error compiling for board Arduino Nano Every.
I been trying to find a solution for a week now with no luck.

Any help would be much appreciated.

Regards,
Thanasis

**Comment by JAndrassy** [comment]
in EspDrv.cpp add
`#define F(string_literal) (reinterpret_cast<const __FlashStringHelper *>(PSTR(string_literal)))`
after includes

**Comment by athdimitriou** [comment]
That worked perfectly. Thank you very much @jandrassy

**Comment by JAndrassy** [comment]
with SDK 3 AT 1.7 or higher, you can use my WiFiEspAT library
