### ISSUE TITLE
ESP8266 Crashes After UDP Packet Overload

### ISSUE THREAD

**Issue by sunnstix** [bportaluri/WiFiEsp#213]
I'm working on a local networking project for my home and part of the architecture results it my RasPi occasionally sending significantly increased UDP numbers of packets to the ESP/Arduino. However, when the speed of this traffic increases significantly over a short period of time, the ESP board seems to crash/hang (from what I suspect is a lack of memory). Has anyone had similar issues with this library or is there a workaround to ignore packets if the ESP buffer is full?

**Comment by JAndrassy** [comment]
if you can upgrade the AT firmware to 2.7.4 you can try my WiFiEspAT library

**Comment by sunnstix** [comment]
Awesome - made the switch and upgraded my firmware and it now works like a charm. Thanks!
