### ISSUE TITLE
TIMEOUT in same position every time on large HTTP header 

### ISSUE THREAD

**Issue by aimass** [bportaluri/WiFiEsp#218]
Hi there,

Environment:

- ESP8266 Grove UART with SDK 1.1.0
- Arduino Uno R3
- Grove powered by the UNO 3.3V line and level shifters between the UNO lines and the Grove TX/RX
- WiFiEsp 2.2.2
- Software Serial on D7 and D8

Trying to implement a simple HTTP client but as I am reading the return stream it always gets a TIMEOUT: 36 and it's always at the same position 36. By doing some debugging it seems to be choking on this large header sent by Arduino Yun server:

```
Set-Cookie: sysauth=ed6f0055d4e0c4609b5917b2e07e90ef; path=/cgi-bin/luci/;stok=159f7efc71fc95e37b326445cd17768d
```

So is it possible that either the ESP8266 firmware or WiFiEsp is having some issue with this large header ?

Also, not sure if related, but the only way I could get the module to initialize is by doing this (which seems to contradict all the example code):

```
wifiLink.begin(115200);
WiFi.init(&wifiLink);
wifiLink.println("AT+UART_CUR=9600,8,1,0,0");
wifiLink.end();
wifiLink.begin(9600); 

```

TIA,

-- 
Alex

**Comment by JAndrassy** [comment]
if you update the AT firmware to 2.7.5 (SDK 3.0.5), then you can use my newer WiFiEspAT library

**Comment by aimass** [comment]
@JAndrassy thanks for your prompt reply! 

I was trying to avoid firmware update because this little project was supposed to be a simple hack using this old Grove I had laying around for some time, and just wanted to finally use it. 

But it's getting too complicated for the time I can spend on it, so decided to buy an Arduino WiFi to finish the job.  

Having said this, and since I wired the level shifter and the prototype came out really nice, I would like to solve the issue and re-use this prototype in a future project ;-)

I'll try the update sometime in the future and I will follow up on this thread eventually.. closing for now.

Thanks again,

-- 
Alex
