### ISSUE TITLE
Bad constant in EspDrv::getScanNetworks

### ISSUE THREAD

**Issue by pantata** [bportaluri/WiFiEsp#22]
is: if(ssidListNum==WL_SSID_MAX_LENGTH-1) break;
to be: if(ssidListNum==WL_NETWORKS_LIST_MAXNUM-1) break;

or 
comment if(ssidListNum==WL_SSID_MAX_LENGTH-1) break;
and change 
while (idx == NUMESPTAGS)
to 
while ((idx == NUMESPTAGS) && (ssidListNum < WL_NETWORKS_LIST_MAXNUM))

**Comment by bportaluri** [comment]
Fixed in 12e63b176229ebcb6618774f6bbd912e8a95a131
