### ISSUE TITLE
Invalid "ClientSSL " connection directive

### ISSUE THREAD

**Issue by Allen1080211** [bportaluri/WiFiEsp#223]
Today I open my previous project and use the same Arduino code to connect e.g. Line Notification or http://arduino.tips/asciilogo.txt port 443 , but i found that ESP8266 always cannot be connected, please help me how to solve this problem? 

Maybe this library not support TLS1.2 ? and please help me how to do it .

------------------------------------------------------------------------------
Arduino Serial Monitor debug:
------------------------------------------------------------------------------
Starting connection to server...
[WiFiEsp] Connecting to arduino.tips
Connected to server
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Data packet send error (1)
[WiFiEsp] Failed to write to socket 3
[WiFiEsp] Disconnecting  3

Disconnecting from server...

**Comment by JAndrassy** [comment]
the AT firmware doesn't support TLS 1.2

you could switch to use https://github.com/JiriBilek/ESP_ATMod

**Comment by Allen1080211** [comment]
> Thanks JAndrassy for replying me ~
I step by step do it , but I got an error at "step 4. Now upload the ESP_ATMod sketch to the ESP." 

I don't know how to solve it, please tell me, thanks

------------------------------------------------------------------
Error message
-------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/52644706/233961023-34c7d11e-99b7-4be2-b4f3-e3ff586e1b99.png)

------------------------------------------------------------------
Tool Setting
-------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/52644706/233960309-3850a38e-6876-4e11-b585-ed7ebdafc672.png)

**Comment by JAndrassy** [comment]
use esp8266 platform version 2.7.4

**Comment by Allen1080211** [comment]
Oh, very appreciated JAndrassy for helping me solve it. I am from Taiwan. Thank you!
![image](https://user-images.githubusercontent.com/52644706/234154347-e1b11832-13d8-4dff-9c46-e9e56b82b014.png)

**Comment by JAndrassy** [comment]
I recommend you to switch to my WiFiEspAT library.
https://github.com/JAndrassy/WiFiEspAT#Why-a-new-wifiesp-library
