### ISSUE TITLE
wifiStartAP command

### ISSUE THREAD

**Issue by ricmail85** [bportaluri/WiFiEsp#24]
Hi,

I'm trying to setup an AccessPoint with ESP8266. My problem is related to the scannetwork function. It only works if espmode is 1 (station) or 3 (station+AP). It does not work in espmode=2 (AP). 
Therefore, if I setup an AP (espmode=2), there is no way to scan active networks. I modified the line "if (sendCmd(F("AT+CWMODE_CUR=2"))!=TAG_OK)" in EspDrv.cpp to "if (sendCmd(F("AT+CWMODE_CUR=3"))!=TAG_OK)" and everuthing works like a charm.

Would not be this the best way to setup an AP with ESP?
Thanks a lot!

PS: is it possible to have the espmode variable as public instead of private? This is useful in order to check the current esp setup.

**Comment by bportaluri** [comment]
Sorry but why do you need to scan networks if you are in AP mode?
I can't see any any value in it?
I would like to keep the two modes separate.

**Comment by ricmail85** [comment]
I m doing an AP that is used by the user to scan networks around. When the
user chose his network with a password, the AP is switched to station in
order to connect to Internet.

If the esp is in pure AP mode, it is not possible to scan for network,
while in the hybrid mode it is.

Bye
Il 22/feb/2016 22:40, "Bruno" <notifications@github.com> ha scritto:

**Comment by bportaluri** [comment]
Nice example!
Let me fix it...

**Comment by bportaluri** [comment]
Fixed in c2beedce7229359a8998eb55c174b757cbe7f76d
Will be included in next release
