### ISSUE TITLE
UDP Server does not work

### ISSUE THREAD

**Issue by SukkoPera** [bportaluri/WiFiEsp#25]
The attached sketch, based on an official WiFi shield tutorial (https://www.arduino.cc/en/Tutorial/WiFiSendReceiveUDPString - with obvious modifications) is supposed to setup a UDP server socket which will listen for packets.

Although, it seems that the socket is not actually started and the sketch will never receive anything.

[WiFiUDPServerExample.zip](https://github.com/bportaluri/WiFiEsp/files/133411/WiFiUDPServerExample.zip)

**Comment by bportaluri** [comment]
Yes you are right I'm working on it...

**Comment by SukkoPera** [comment]
Ok, great :). I will be happy to help with the testing, if you want.

**Comment by bportaluri** [comment]
Fixed in release 1.6.
Can you please test it.

**Comment by bportaluri** [comment]
@SukkoPera can you please confirm it works for you?

**Comment by SukkoPera** [comment]
Sorry for the delay, I've been busy for the last couple of days. Thanks a lot! I will test it tomorrow and will report here.

**Comment by SukkoPera** [comment]
Sorry for the delay, I've been busy for the last couple of days. Thanks a lot! The attached example seems to work fine. I will make more complex tests tomorrow and will report my findings here.

**Comment by SukkoPera** [comment]
I can now confirm that all of my tests seem to be successful. If I find any new bugs, I will open new issues. Great job, thanks again!
