### ISSUE TITLE
Compile Error for Arduino Zero

### ISSUE THREAD

**Issue by qbiq** [bportaluri/WiFiEsp#26]
If I try to compile a sketch using i nthe Arduino IDE using the SAMD architecture (Arduino Zero), I get the following error:

`C:\Users\quino\Documents\Arduino\libraries\WiFiEsp\src/utility/RingBuffer.h:23:7: error: redefinition of 'class RingBuffer'``

Removing the lines 30,31 & 32 solves the compilation errors:
`//#include "utility/EspDrv.h"

//#include "utility/RingBuffer.h"

//#include "utility/debug.h"`

But then I have a new issue:
`'WL_IDLE_STATUS' was not declared in this scope`

**Comment by pantata** [comment]
My fix for Arduino M0:
 - rename files and class RingBuffer -> RingBuffer2 
 - EspDrv.cpp: add macro
```
#if defined(__SAMD21G18A__)
#define vsnprintf_P  vsnprintf
#endif
```
 - and I add TCP_ prefix to enum wl_tcp_state (conflict with Keypad lib)

**Comment by Urs-O** [comment]
This Bug is also been adressed by Pull Request #27
