### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by sabas1080** [bportaluri/WiFiEsp#29]
Hi

Thanks for you work, excellent library

I have a question: support SSL command?

http://bbs.espressif.com/viewtopic.php?f=46&t=1703

`Optimized command AT+CIPSTART. The device can function as SSL client, and one SSL connection can be created at most.`

Thanks

**Comment by bportaluri** [comment]
Why not?
Let me work on it...

**Comment by bportaluri** [comment]
It seems the SSL support in new firmware is not working.
I cannot make an SSL connection to google.
AT+CIPSTART=1,"SSL","www.google.com",443

Have you tried ?

**Comment by WheresWally** [comment]
A quick test.

---------------------
>> AT+CIPSTART="SSL","www.google.com",443

---------------------
AT+
AT+CIPSTART="SSL","www.google.com",443



busy p...
Link type ERROR

ERROR
---------------------
>> at+GMR

---------------------
at+
at+GMR



busy p...
AT version:0.51.0.0(Nov 27 2015 13:37:21)
SDK version:1.5.0
compile time:Nov 27 2015 13:57:56
OK

**Comment by joysfera** [comment]
FYI, with SDK 1.5.2 it just reboots:

AT+CIPSSLSIZE=4096

OK
AT+CIPSTART="SSL","iot.espressif.cn",8443

 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

I'll try the boot version of FW (this was noboot one).

Petr

WheresWally píše v So 27. 02. 2016 v 07:32 -0800:

**Comment by joysfera** [comment]
With SDK 1.5.2 BOOT mode:

AT+CIPSSLSIZE=4096

OK
AT+CIPSTART="SSL","www.google.com",443

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset

Still reboots. Weird.

Petr


WheresWally píše v So 27. 02. 2016 v 07:32 -0800:

**Comment by joysfera** [comment]
Guys, I just got the SSL working _after upgrading my esptool.py_! Yes, I
was apparently using an old flasher that did not flash the firmware
properly. What a ...!

BTW, Espressif guys have been very patient with me and guided me through
until I got it fixed (it's been a flash size issue, apparently it must
be specified properly and must be at least 8 Mbit).

Anyway, this is how it's working now (note that SPI Flash Size):

AT+RST

OK

 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x40100000, len 816, room 16 
tail 0
chksum 0x8d
load 0x3ffe8000, len 788, room 8 
tail 12
chksum 0xcf
ho 0 tail 12 room 4
load 0x3ffe8314, len 288, room 12 
tail 4
chksum 0xcf
csum 0xcf

2nd boot version : 1.2
  SPI Speed      : 40MHz
  SPI Mode       : QIO
  SPI Flash Size : 8Mbit
jump to run user1

rdǃ;$ğ
ready
AT+GMR
AT version:0.60.0.0(Jan 29 2016 15:10:17)
SDK version:1.5.2(80914727)
compile time:Jan 29 2016 19:07:08
OK
AT+CWMODE=1

OK
AT+CWJAP="ssid","password"
WIFI CONNECTED
WIFI GOT IP

OK
AT+CIPSSLSIZE=4096

OK
AT+CIPSTART="SSL","sophics.cz",443
CONNECT

OK
CLOSED

Petr

**Comment by bportaluri** [comment]
Thank you @joysfera. I managed to make it work reflashing the ESP baby.
SSL support implemented in 61aa6100eabcb829eb2e68020fe4ed035d602467
