### ISSUE TITLE
Weird EspDrv::wifiConnect behavior

### ISSUE THREAD

**Issue by marcfon** [bportaluri/WiFiEsp#3]
I have no clue why but I had to change 299-304 into `return sendCmd(cmdBuf, 10000) == TAG_OK;` to make EspDrv::wifiConnect return the correct status. With the current code the if statement was not evaluating correctly although the values were correct. This is with SDK 0.9.5 and Arduino 1.6.5.

**Comment by bportaluri** [comment]
Can you try the new release?
It works with SDK 1.1.1 and above.
