### ISSUE TITLE
how do you set the IP address of an AP?

### ISSUE THREAD

**Issue by joysfera** [bportaluri/WiFiEsp#31]
Sorry I can't find any way of configuring the IP address of an AP. Basically the "AT+CIPAP" wrapper. What am I overlooking, please?

**Comment by joysfera** [comment]
maybe it's somehow related to the unfinished implementation of config(IPAddress) - the EspDrv class implements config() for a station ("AT+CIPSTA") but is missing code for an AP ("AT+CIPAP"). And the WiFiEsp's config() is empty.

**Comment by bportaluri** [comment]
Fixed in fda7e19206f4c4470e66252192675dab789984fa
Can you please confirm it works for you?
