### ISSUE TITLE
WebServer example does not work at all

### ISSUE THREAD

**Issue by joysfera** [bportaluri/WiFiEsp#32]
The WebServer example does not work at all - it does not open up the port 80:

```
Attempting to connect to WPA SSID: Twim
You're connected to the network
SSID: Twim
IP Address: 192.168.3.144

To see this page in action, open a browser to http://192.168.3.144

$ telnet 192.168.3.144 80
Trying 192.168.3.144...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by bportaluri** [comment]
I have tested it on my ESP-01 plugged on Arduino Uno and it works.
Can you please check there is no firewall blocking you?

**Comment by joysfera** [comment]
Bruno píše v Ne 28. 02. 2016 v 13:33 -0800:
> I have tested it on my ESP-01 plugged on Arduino Uno and it works.

I have tested it on my ESP-07 on Pro Mini and it didn't open the port.

> Can you please check there is no firewall blocking you?

there's no firewall involved. I have been comparing your WiFiEsp with my
arduino-ESP8266 library, switching between them back and forth. Your
WiFiEsp simply does not open the port. No idea why.

Petr

**Comment by joysfera** [comment]
BTW, I use AT v0.60 on SDK 1.5.2 and ESP is connected to HW Serial.

**Comment by sabas1080** [comment]
And from your browser work?

**Comment by joysfera** [comment]
sabas1080 píše v Po 29. 02. 2016 v 18:44 -0800:
> And from your browser work?

The reason I attached the telnet output was that it's a clear evidence.
If I just said "browser cannot open it" you could argue that I mistyped
the IP address or something. With the copy&pasted telnet output you
can't question that.

I could run nmap against the ESP8266 to see if there are any other ports
open. Would that be useful? I don't think so.

I could also enable the internal logging of WiFiEsp to see if the right
AT commands were executed, compare that with the AT commands
documentation and make sure all the required commands are called in the
right order.

I could even manually enter all the commands in a terminal session and
try to reproduce the problem.

But I don't have time at this moment for any of my ideas listed above.

BTW, I'm working with Espressif on the SSL reboot issue - I find that
more important right now.

**Comment by bportaluri** [comment]
@joysfera If you can enable WiFiEsp debugging it would be good to understand what's happening.
I agree with you the SSL issue is more important since this problem seems not to be so common.

@sabas1080 Does the WebServer example works for you?
