### ISSUE TITLE
Can't connect to server If I try without Computer

### ISSUE THREAD

**Issue by atideath** [bportaluri/WiFiEsp#33]
It is working very well If Arduino is connected to computer. If I will use standalone Arduino (without computer only power supply) It can't connect to server. It have a IP, can I ping from the computer but It can't send data to the server.

My code is: 
[Code](http://pastebin.com/FupfGbUy)

**Comment by dapug** [comment]
No code change between where it works and doesnt?  Is it within the same range?  And does it have sufficient power?

**Comment by Rustam96** [comment]
I sketch after boot. Working
Arduino disabled, switched says "Connection failed"
You decide this question?

**Comment by Rustam96** [comment]
Add  to (setup)
`Serial1.println ("AT+RESTORE");`
Fix. I correct it?

**Comment by bportaluri** [comment]
I don't understand how the restore command can help. It restores the default settings.
I do a soft reset in the setup method.

**Comment by Rustam96** [comment]
Tested AT+RST program ESPlorer
if  set the address AT+CIPSTA=192.168.1.50.
AT+RST does not remove it.
What he does not remove.
Or firmware 1.1.2 is not working correctly

**Comment by bportaluri** [comment]
The EspDrv.reset method enables DHCP with AT+CWDHCP=1,1 command.
If you want to set the IP you can use WiFiEsp.config or WiFiEsp.configAP methods.

**Comment by Rustam96** [comment]
Sorry for my English.
The objective was to verify that the command clears
But the example of the IP, the team is not all cleans

**Comment by atideath** [comment]
I found the problem. The Arduino Uno run out of memory. I removed more code, it was working correctly. I changed the uno to bigger arduino mega.
