### ISSUE TITLE
UdpNTPClient example does not work reliably

### ISSUE THREAD

**Issue by SukkoPera** [bportaluri/WiFiEsp#34]
I can't understand why exactly, but the UdpNTPClient mostly fails.

NTP packets are 48 bytes long, and Udp.parsePacket () correctly returns 48. But then, the buffer returned by Udp.read() only contains the first 33 bytes with padding zeroes. I have traced this problem to EspDrv::timedRead() timing out after the 33th byte, but I can't understand why this happens.

To add to the weirdness, the following Udp.read() calls only return 15 bytes (which is 48 - 33, by the way!), but they do not look to be the "missing" bytes of the previous message.

I thought this could be caused by the ring buffer size, so I tried increasing it but to no avail.

The NTP reply contains 8 consecutive zero bytes before the 33th byte (bytes 25-32), maybe this is causing the misbehaviour?

Note that since the actual time that gets decoded by the sketch is at bytes 40:43, the sketch will always say that time is 6:28:16, which corresponds to all zeroes at such positions.

**Comment by SukkoPera** [comment]
OK, I have just fixed this by increasing the size of the serial buffer. I am currently using my ESP with an Arduino Mega through serial port 3, so I changed this line

    #define SERIAL_RX_BUFFER_SIZE 64

in HardwareSerial.h, to say 128.

But... can this be worked around?

**Comment by bportaluri** [comment]
I also had the same problem.
That's why I have put this workaround in the UdpNTPClient example header comment.
Unfortunately there is no way to fix this in the WiFiEsp library.

**Comment by SukkoPera** [comment]
Oh, you mean that HUGE header comment I only saw after you mentioned it?

LOL, I wasted a lot of time getting to the same workaround on my own!

**Comment by torquato1** [comment]
the UdpNTPClient example give me the same unix time  2085978496
48 packet received
Seconds since Jan 1 1900 = 0
Unix time = 2085978496
The UTC time is 6:28:16
13
packet received
Seconds since Jan 1 1900 = 0
Unix time = 2085978496
The UTC time is 6:28:16
48
packet received
Seconds since Jan 1 1900 = 0
Unix time = 2085978496
The UTC time is 6:28:16
13
packet received
Seconds since Jan 1 1900 = 0
Unix time = 2085978496
The UTC time is 6:28:16

**Comment by SukkoPera** [comment]
@torquato1 Look at the top of the example: there's a comment saying that you need to modify some Arduino header file, just do it.

**Comment by torquato1** [comment]
I made the change "For SoftwareSerial change _ SS_MAX_RX_BUFF in Arduino\hardware\arduino\avr\libraries\SoftwareSerial\SoftwareSerial.h"
but nothing changes

**Comment by torquato1** [comment]
Sorry I found the problem. I edited the file in folder other than the one from which the compiler was. thanks and Hello
