### ISSUE TITLE
Cannot initialize ESP module

### ISSUE THREAD

**Issue by rorschach217** [bportaluri/WiFiEsp#35]
i am running example code from this library.i.e. WebClient

i am getting this out put on Seria Monitor
[WiFiEsp] Initializing ESP module
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Cannot initialize ESP module

then after some time

[WiFiEsp] Failed to connected to Taneja
SSID: [WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] No tag found

[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] No tag found
IP Address: 0.0.0.0
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] No tag found
Signal strength (RSSI):0 dBm

i have connected the circuit as below
esp8266 rx to pin 5
esp8266 tx to pin 6
5v to voltage regulator Vin and voltage regulator Vout to esp8266 vcc and CH_PD
gnd to gnd and then after uploading the program it gives above output.

the code is like this
`#include "WiFiEsp.h"

// Emulate Serial1 on pins 6/7 if not present
#ifndef HAVE_HWSERIAL1
#include "SoftwareSerial.h"
SoftwareSerial Serial1(6, 7); // RX, TX
#endif

char ssid[] = "Taneja";            // your network SSID (name)
char pass[] = "taneja1993";        // your network password
int status = WL_IDLE_STATUS;     // the Wifi radio's status

char server[] = "arduino.cc";

// Initialize the Ethernet client object
WiFiEspClient client;

void setup()
{
  // initialize serial for debugging
  Serial.begin(115200);
  // initialize serial for ESP module
  Serial1.begin(9600);
  // initialize ESP module
  WiFi.init(&Serial1);

  // check for the presence of the shield
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi shield not present");
    // don't continue
    while (true);
  }

  // attempt to connect to WiFi network
  while ( status != WL_CONNECTED) {
    Serial.print("Attempting to connect to WPA SSID: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network
    status = WiFi.begin(ssid, pass);
  }

  // you're connected now, so print out the data
  Serial.println("You're connected to the network");
  
  printWifiStatus();

  Serial.println();
  Serial.println("Starting connection to server...");
  // if you get a connection, report back via serial
  if (client.connect(server, 80)) {
    Serial.println("Connected to server");
    // Make a HTTP request
    client.println("GET /asciilogo.txt HTTP/1.1");
    client.println("Host: arduino.cc");
    client.println("Connection: close");
    client.println();
  }
}

void loop()
{
  // if there are incoming bytes available
  // from the server, read them and print them
  while (client.available()) {
    char c = client.read();
    Serial.write(c);
  }

  // if the server's disconnected, stop the client
  if (!client.connected()) {
    Serial.println();
    Serial.println("Disconnecting from server...");
    client.stop();

    // do nothing forevermore
    while (true);
  }
}

void printWifiStatus()
{
  // print the SSID of the network you're attached to
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your WiFi shield's IP address
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // print the received signal strength
  long rssi = WiFi.RSSI();
  Serial.print("Signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}`

**Comment by rorschach217** [comment]
before voltage regulator i am giving vcc direct from uno 3.3v pin

**Comment by sabas1080** [comment]
You have correct TX and RX pins, which is the baud rate of ESP8266?

**Comment by rorschach217** [comment]
I don't know... How do i found out ..?

**Comment by WheresWally** [comment]
The 3,3v reg on Uno board only gives 30-100mA, ESP needs 200+mA.
so a LM3111 or similar 3V source  is a must, and add some 10uF caps.

Try swapping the RxTx wires. I often get them wrong first time.

[http://randomnerdtutorials.com/esp8266-troubleshooting-guide/](url)

have a look at how i used the uno serial by holding the uno reset.
[https://github.com/bportaluri/WiFiEsp/issues/9](url)

**Comment by rorschach217** [comment]
@sabas1080 i found out the baud rate of my esp8266 its 115200.

and @WheresWally thank you for comment and suggestion i will try your suggestion and let you know.

thank you.

**Comment by rorschach217** [comment]
Thank you @WheresWally for your suggestion i changed my circuit and added 10uF capacitor and esp gives responce properly with general AT commands like AT, AT+GMR, AT+CWMODE=1, AT+CWJAP="xxxxx","xxxxx". 
it connects the esp to my wifi. i can see the entry of esp in my router i.e. 192.168.1.1 
but when i tries the AT+CIPSTART=0,"TCP","www.google.com","80" command it gives error in serial monitor.

**Comment by rorschach217** [comment]
and my esp8266 gives to much garbage values what could cause of this ?
like this
>>>> AT+CWLAP

AT+CWLAP

+CWLAP:(3,"belkin.3924",-93,"08:87:3b:60:29:14",1,18)
+CWLAP:(4,"Taf07),,IÒÒŠ
L-51A-91y,:)*é¹‰béé…ŠJ
"-Ò‚áj
¥Bºš’‚«½‰bé‰‚‚ŠJ
,tË¡Ékf45

**Comment by dapug** [comment]
I also get TIMEOUT, Cannot initialize ESP module, No Tag Found.  I don't get it.  AT commands work fine, the ESP-01 has no issue.  Running sdk v1.4.0, 512k flash (4Mbit).  What is WifiESP doing?

-- off topic--
@rorschach217, thats not how you ping a website.  Try this:

AT+CIPMUX=1
AT+CIPSTART=4,"TCP","www.google.com",80
AT+CIPSEND=4,8
GET / HTTP/1.1\r\nHost: google.com\r\n\r\n

**Comment by rorschach217** [comment]
@dapug  thank you.
will try this method. and can you give me the hint about AT+CIPSEND=4,8 , what is 8 ? i know that is length of data but which data what i am sending or which i am going to receive.

**Comment by dapug** [comment]
BTW, I resolved my TIMEOUT / No Tag issue by configuring the ESP-01 to use a lower baud.  Default settings from a newly flashed firmware sets ESPs to 115200, but you must use **9600** for SoftwareSerial (most of the WifiESP samples). See [this post](https://github.com/bportaluri/WiFiEsp/issues/37).

Use this command:
`AT+UART_DEF=9600,8,1,0,0`

For the SEND command, even when doing a GET request you are still sending the server (in this case the ESP device as a server) a request.  So the length of the GET request itself has to be specified.  This is pretty low level stuff, which is why it's nice to have a library like WifiESP to wrap and abstract it!

First take a look at the GET request you are making, like so:
`GET /about HTTP/1.1\r\nHost: google.com\r\n\r\n`

Now count the characters (including spaces), but be sure to count \r and \n as ONE character AND do not count the LAST \r\n at all.  So your total here would be **39** (not 8, I was wrong in my earlier post).  So, AT+CIPSEND=39 will get the /about page of google.

**Comment by rorschach217** [comment]
@dapug thank you for your effort. this issue originally for esp initialization. i have created new repository for that [https://github.com/rorschach217/ESP_API](url) and opening the new issue for API GET methods using esp. you can give me further instruction on that repository.
thank you.

**Comment by rorschach217** [comment]
new issue opened here [https://github.com/rorschach217/ESP_API/issues/1](url)

**Comment by Biswanath00** [comment]
> AT+UART_DEF=9600,8,1,0,0

Thanks sir
