### ISSUE TITLE
Older ESP-01 Firmware Support

### ISSUE THREAD

**Issue by dapug** [bportaluri/WiFiEsp#37]
I see that most ESP-01 modules come with v.0.9.2 loaded. I noticed that WifiEsp rejects that.  Any reason you need a higher version? Are there some features that depend on it?

I tried flashing to no avail using every tutorial on the entire web, including and especially this one: http://yaab-arduino.blogspot.it/2015/12/flashing-esp8266-firmware-arduino.html. 

My ESP-01 devices refuse to work with v1.x.  I can flash them with NodeMCU and it works fine, so I know my hardware and wiring for programming are good.

I also read through this post https://github.com/bportaluri/WiFiEsp/issues/9, but my issue is different, in that flashing succeeds, no errors, but the device will NOT respond to AT commands (acts as though it's dead or without firmware).  Any tips are appreciated.  But in the meantime, if WifiESP didn't have this requirement, that would also be helpful.  I've looked at about 10 other wifi libraries and WifiESP is the only one that actually has activity and changes more recently than a full year ago.

**Comment by dapug** [comment]
UPDATE:
ok, I got it working.  There are TWO important things to know about some of the ESP-01 modules

1. **4Mbit is NOT supported in v1.5.1 and higher**!  I reverted to **v1.5.0** and it worked. If your module is 8Mbit, this is a non-issue.
2. You must run at **115200 baud** to talk to the device. 9600 no worky like it did with v.0.9.2

Notes on v1.5.0:

- This has a patch, so you need to download from here: http://bbs.espressif.com/viewtopic.php?f=46&t=1451
- You must follow the "readme.txt" instructions about addresses on the bin files you are loading for the 4Mbit device

**Comment by bportaluri** [comment]
Be aware that 115200 will not work with software serial. With Arduino Uno you must set the a lower baud rate like described in [this post]( http://yaab-arduino.blogspot.com/2015/12/flashing-esp8266-firmware-arduino.html).
The AT command to change the default baud rate is AT+UART_DEF=9600,8,1,0,0

**Comment by dapug** [comment]
Good point, thanks. Be sure to set the baud lower after a firmware flash since firmware defaults it to 115200.  

For anyone reading this later, if you are getting the "Timeout", "Cannot initialize ESP module", and "No Tag Found", this could be your issue - check and set baud to 9600.

Overall, this issue is solved.  Closing.

**Comment by Avcu** [comment]
Thank you so much guys. I had also same problem...

**Comment by diegommarino** [comment]
Thank you so muvh @bportaluri and @dapug ! It worked like a charm after set the baud rate with the command "AT+UART_DEF=9600,8,1,0,0".

This lib is perfect to use with [PubSubClient lib](https://github.com/knolleary/pubsubclient). With a few adaptations it flows like water :yum: .

Here is my adapted code for PubSubClient

```c#
/*
 /*
 Basic Arduino UNO + ESP8266-01 MQTT example
 
 It connects to an MQTT server then:
  - publishes "hello world" to the topic "outTopic" every two seconds
  - subscribes to the topic "inTopic", printing out any messages
    it receives. NB - it assumes the received payloads are strings not binary
  - If the first character of the topic "inTopic" is an 1, switch ON the Arduino Led,
    else switch it off
 It will reconnect to the server if the connection is lost using a blocking
 reconnect function. See the 'mqtt_reconnect_nonblocking' example for how to
 achieve the same result without blocking the main loop.
*/

#include "WiFiEsp.h"
#include <PubSubClient.h>

// Emulate Serial1 on pins 6/7 if not present
#ifndef HAVE_HWSERIAL1
#include "SoftwareSerial.h"
SoftwareSerial Serial1(6, 7); // RX, TX
#endif

// Update these with values suitable for your network.
char ssid[] = "MQTT_TEST";            // your network SSID (name)
char password[] = "raspberry";        // your network password
int status = WL_IDLE_STATUS;     // the Wifi radio's status
const char* mqtt_server = "192.168.1.100";

WiFiEspClient espClient;
PubSubClient client(espClient);
long lastMsg = 0;
char msg[50];
int value = 0;
int built_in_led = 13;

void setup_wifi() {

  delay(10);
  // We start by connecting to a WiFi network
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();

  // Switch on the LED if an 1 was received as first character
  if ((char)payload[0] == '1') {
    digitalWrite(built_in_led, LOW);   // Turn the LED on (Note that LOW is the voltage level
    // but actually the LED is on; this is because
    // it is acive low on the ESP-01)
  } else {
    digitalWrite(built_in_led, HIGH);  // Turn the LED off by making the voltage HIGH
  }

}

void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("ESP8266Client")) {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("outTopic", "hello world");
      // ... and resubscribe
      client.subscribe("inTopic");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}

void setup() {
  pinMode(built_in_led, OUTPUT);     // Initialize the BUILTIN_LED pin as an output
  Serial.begin(9600);
  Serial1.begin(9600);
  // initialize ESP module
  WiFi.init(&Serial1);
  setup_wifi();
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);
}

void loop() {

  if (!client.connected()) {
    reconnect();
  }
  client.loop();

  long now = millis();
  if (now - lastMsg > 2000) {
    lastMsg = now;
    ++value;
    snprintf (msg, 75, "hello world #%ld", value);
    Serial.print("Publish message: ");
    Serial.println(msg);
    client.publish("outTopic", msg);
  }
}
```

**Comment by FernandoGarcia** [comment]
Hi @diegommarino!

Can you publish and subscribe using this code?

I have tested this code but I'm not able to receive any message.

The publish function is working very fine.

Best regards.

**Comment by hatfieldr** [comment]
Hi @diegommarino!

I also have the same problem
The code works fine & publishes to outTopic but no messages are received on inTopic
client.subscribe("inTopic") returns true but no message is received

Any help would be appreciated!

Regards

**Comment by stanleyseow** [comment]
I got this working half half, I m using AltSoftSerial ( pin 8,9 on UNO ) that can goes up to 57600 without any problems....

Able to send and received published/subscribed messages ....

**Comment by amrithmmh** [comment]
this post actually solved my problem thank you for reporting the solution
