### ISSUE TITLE
TIMEOUT on a GET request to "server"

### ISSUE THREAD

**Issue by dapug** [bportaluri/WiFiEsp#38]
I'm getting really unpredictable results when running the WifiESPLed sample.  

- It always connects to the network (sometimes after fail/retry)
- It often fails to start the server (about 50/50)
- When it does start, I can hit the IP from my browser
- Sometimes it completes the request, page renders fine (shows me the LED is 0, etc)
- However, it ALWAYS times out at this point, and disconnects the request.
- It seems to be in a crashed state at this point too, further requests just timeout at the browser

Here is my output:

```
[WiFiEsp] Initializing ESP module
[WiFiEsp] Initilization successful - 1.4.0
Attempting to connect to WPA SSID: xxxx
[WiFiEsp] Connected to xxxx
You're connected to the network
SSID: xxxx
IP Address: 192.168.3.41

To see this page in action, open a browser to http://192.168.3.41

[WiFiEsp] Server started on port 80
[WiFiEsp] New client 0
New client
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Data packet send error (2)
[WiFiEsp] Failed to write to socket 0
[WiFiEsp] Disconnecting  0
[WiFiEsp] Disconnecting  0
Client disconnected
```

**Comment by dapug** [comment]
I'm also finding the same timeout issue when the device is acting as a client making a simple request, such as to arduino.cc/asciilogo.txt in the WebClient example.

**Comment by bportaluri** [comment]
Can you please enable debugging in WiFiEsp\src\utility\debug.h file?
It should tell you more about what's happening.

**Comment by voordeh** [comment]
I have the same problem doing the udp time example
I have tested the same unit with manual AT commands at it works. Is this a timing problem??

**Comment by sacot41** [comment]
I have simillar issue with my setup. I use a arduino uno with SoftwareSerial at 115200 baud to communicate with my esp-01. But, SoftwareSerial doesn't support very well 115200... Same code on my mega2560 with a real Serial and no problem. 

I will test to down speed my esp-01 with command : AT+UART_DEF=9600,8,1,0,0

**Comment by sacot41** [comment]
Finally, I used the command "Serial1.write("AT+CIOBAUD=9600");" after "WiFi.init(&Serial1);"
I can't have good result with SoftwareSerial and a bigger baud rate on my arduino uno.

May be adding a method in this library to change baud rate of esp-01 would be a good idea ?

**Comment by bportaluri** [comment]
You can't change the baud rate after the init method because it already sends few AT commands.

If you are going to use the ESP-01 module with Arduino Uno (using software serial) you have to lower the default baud rate because the SoftwareSerial interface maximum speed is around 38400 bps. I suggest to set the ESP module to use 9600 or 19200 bps. To set the correct baud rate use this command:

AT+UART_DEF=9600,8,1,0,0
