### ISSUE TITLE
Closing connection behavior

### ISSUE THREAD

**Issue by marcfon** [bportaluri/WiFiEsp#4]
Sending `client.println("Connection: close");` along with a request makes `client.stop()` throw an error 

AT+CIPCLOSE=0
link is not
ERROR

Not calling `client.stop()` at all poses the problem that WiFiEsp thinks the connection is still active and runs out of sockets to use.

**Comment by bportaluri** [comment]
I think this is solved in the new version.
It works only with SDK 1.1.1 and above.
Can you try it?
