### ISSUE TITLE
try webclient example , got that error .

### ISSUE THREAD

**Issue by spencer1979** [bportaluri/WiFiEsp#42]
C:\Users\wchen\Documents\Arduino\libraries\WiFiEsp\src\utility\EspDrv.cpp: In static member function 'static bool EspDrv::getNetmask(IPAddress&)':
C:\Users\wchen\Documents\Arduino\libraries\WiFiEsp\src\utility\EspDrv.cpp:503:10: error: 'class IPAddress' has no member named 'fromString'
     mask.fromString (buf);
          ^
C:\Users\wchen\Documents\Arduino\libraries\WiFiEsp\src\utility\EspDrv.cpp: In static member function 'static bool EspDrv::getGateway(IPAddress&)':
C:\Users\wchen\Documents\Arduino\libraries\WiFiEsp\src\utility\EspDrv.cpp:516:8: error: 'class IPAddress' has no member named 'fromString'
     gw.fromString (buf);
        ^
Error compiling.

**Comment by bportaluri** [comment]
I don't have this error.
What board are you compiling?
What version of the library do you have?

**Comment by artronic84** [comment]
Hello Bruno,

I get the same error while compiling for Arduino Uno in IDE 1.6.6 with both version 2.1.1 and 2.1.2
I am about to try with 1.6.9

Thank you.

**Comment by bportaluri** [comment]
Any news?

**Comment by artronic84** [comment]
Bruno, sorry but I edited the thread instead of adding a reply, so you probably didn't notice it.

1.6.9 worked fine without compile errors

**Comment by Luffare1** [comment]
I Have the same problem, any fix or do I have to back my IDE? 
I have v1.7.10
