### ISSUE TITLE
ESP8266WifFi

### ISSUE THREAD

**Issue by frankygoop** [bportaluri/WiFiEsp#47]
Hi, this is not like an issue but a question. I had used this library extensively and I am very happy. I developed the project for Mega2560 using the Esp8266. I just tried to compile it for ESP8266 12E Nodemcu and had the following error. 
"Arduino\libraries\WiFiEsp\src\utility\EspDrv.cpp:20:26: fatal error: avr/pgmspace.h: No such file or directory. 
#include <avr/pgmspace.h>"

I want to know if the your library and the Nodemcu are not compatible. I will have to modify many lines of code.

Sorry if I did a stupid question. 

Thanks

**Comment by bportaluri** [comment]
The WiFiEsp library is for using the ESP8266 module as a WiFi shield for Arduino. If you already have and ESP board you can use the built-in wifi capabilities.

**Comment by iPAS** [comment]
Probably, changing the code to:
```c++
#ifdef ARDUINO_ARCH_AVR
#include <avr/pgmspace.h>
#else
#include <pgmspace.h>
#endif
```
