### ISSUE TITLE
Unsupported firmware warning

### ISSUE THREAD

**Issue by oguzcicek** [bportaluri/WiFiEsp#48]
Hello , thank you for this great library.

i upgraded my ESP-01 but i have an error :
`Warning: Unsupported firmware`

when i write AT+GMR i can see this version : `0018000902`

when i use your example codes i have these errors 

```
[WiFiEsp] Warning: Unsupported firmware 
Attempting to connect to WPA SSID: mywifi
[WiFiEsp] Failed connecting to mywifi
```

**Comment by bportaluri** [comment]
WiFiEsp supports ESP SDK version 1.1.1 and above (AT version 0.25 and above).
0018000902 doesn't seems to be a recent firmware

**Comment by w3hacker** [comment]
AT version:0.40.0
SDK version:1.3.0

**esp8266-01 not support too**

**Comment by arthurzinx** [comment]
@oguzcicek how did you resolve this problem?

**Comment by oguzcicek** [comment]
i upgraded again and find right version.

**Comment by cborchez** [comment]
@oguzcicek how do you do that? I'm getting the [WiFiEsp] Warning: Unsupported firmware and I don't know how to upgrade fw

**Comment by arthurzinx** [comment]
@cborchez you just need to connect the gpio 0 to low in order to get the upgrade mode.
https://www.filipeflop.com/wp-content/uploads/2016/01/Circuito_Arduino_ESP8266.png

**Comment by Gomezzzzz** [comment]
> i upgraded again and find right version.

May I ask where to find the right version?

**Comment by jandrassy** [comment]
on manufacturers [download page](http://espressif.com/en/support/download/at?keys=&field_type_tid%5B%5D=14)
