### ISSUE TITLE
Is it possible user software serial with custom pins?

### ISSUE THREAD

**Issue by array81** [bportaluri/WiFiEsp#5]
Is it possible user software serial with custom pins?
I think the software serial works only if I connect the module to pins 6 and 7. Why?
I'd like use it with any pins by set pins by code.

**Comment by joysfera** [comment]
SoftwareSerial library works with any two pins. AltSoftSerial library requires two fixed pins.

**Comment by bportaluri** [comment]
WiFiEsp uses the SoftwareSerial library to emulate the second serial port if not available.
The serial pins are defined in utility/EspDrv.cpp file.

**Comment by WheresWally** [comment]
So in setup()
  WiFi.init(9600);  // initialize ESP serial port with default baud rate 9600

we would like to be able to also add the RX and TX pins for software Serial
like this

  WiFi.init(9600,2,3);  // initialize ESP serial port with default baud rate 9600, RX,TX defaults 6,7

Please

**Comment by array81** [comment]
Use something like WiFi.init(9600,2,3); is more simple that change source code :)

**Comment by torchris** [comment]
I agree this would be a great enhancement. I'm using an Arduino Pro Mini clone so I prefer to dial back the speed to 9600 and I am using non-standard pins for the SoftWareSerial. When you update the library (which is awesome), I need to remember to chase down the pins and baud rate in the library source.

**Comment by bportaluri** [comment]
I have released the new version with a different initialization procedure. Here is an example.
```
#ifndef HAVE_HWSERIAL1
#include "SoftwareSerial.h"
SoftwareSerial Serial1(6, 7); // RX, TX

void setup()
{
  // initialize serial for ESP module
  Serial1.begin(9600);
  // initialize ESP module
  WiFi.init(&Serial1);
...
```

I have also updated the examples.
Please give it a try and tell me if it works for you.

**Comment by torchris** [comment]
Thanks! I'll give it a test later on!

**Comment by torchris** [comment]
Works like a charm! Many thanks! I'm using it to upload data to Thingspeak and it's rock solid!!

**Comment by WheresWally** [comment]
Ah yes, I had thought of that way too, but Christmas. Good idea, create the stream and pass that, would work for Hardware serial on a Mega too yes?
Good job.
