### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by acremers87** [bportaluri/WiFiEsp#52]
I am receiving the following errors while using your code.

This is the webserver example code. I'm using Arduino IDE 1.6.5

This is the code, i've added in my ssid and pass and some other stuff to work with my 8266...

`/*
 WiFiEsp example: WebServer

 A simple web server that shows the value of the analog input 
 pins via a web page using an ESP8266 module.
 This sketch will print the IP address of your ESP8266 module (once connected)
 to the Serial monitor. From there, you can open that address in a web browser
 to display the web page.
 The web page will be automatically refreshed each 20 seconds.

 For more details see: http://yaab-arduino.blogspot.com/p/wifiesp.html
*/
#include <PLDuino.h>
#include "WiFiEsp.h"

// Emulate Serial1 on pins 6/7 if not present
#ifndef HAVE_HWSERIAL1
#include "SoftwareSerial.h"
SoftwareSerial Serial1(14, 15); // RX, TX
#endif

char ssid[] = "Linksys2";            // your network SSID (name)
char pass[] = "6046146090";        // your network password
int status = WL_IDLE_STATUS;     // the Wifi radio's status
int reqCount = 0;                // number of requests received

WiFiEspServer server(80);

void setup()
{
    using namespace PLDuino;
  
  PLDuino::init();
  enableESP();
  // initialize serial for debugging
  Serial.begin(9600);
  // initialize serial for ESP module
  Serial1.begin(115200);
  // initialize ESP module
  WiFi.init(&Serial1);

  // check for the presence of the shield
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi shield not present");
    // don't continue
    while (true);
  }

  // attempt to connect to WiFi network
  while ( status != WL_CONNECTED) {
    Serial.print("Attempting to connect to WPA SSID: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network
    status = WiFi.begin(ssid, pass);
  }

  Serial.println("You're connected to the network");
  printWifiStatus();
  
  // start the web server on port 80
  server.begin();
}

void loop()
{
  // listen for incoming clients
  WiFiEspClient client = server.available();
  if (client) {
    Serial.println("New client");
    // an http request ends with a blank line
    boolean currentLineIsBlank = true;
    while (client.connected()) {
      if (client.available()) {
        char c = client.read();
        Serial.write(c);
        // if you've gotten to the end of the line (received a newline
        // character) and the line is blank, the http request has ended,
        // so you can send a reply
        if (c == '\n' && currentLineIsBlank) {
          Serial.println("Sending response");
          
          // send a standard http response header
          // use \r\n instead of many println statements to speedup data send
          client.print(
            "HTTP/1.1 200 OK\r\n"
            "Content-Type: text/html\r\n"
            "Connection: close\r\n"  // the connection will be closed after completion of the response
            "Refresh: 20\r\n"        // refresh the page automatically every 20 sec
            "\r\n");
          client.print("<!DOCTYPE HTML>\r\n");
          client.print("<html>\r\n");
          client.print("<h1>Hello World!</h1>\r\n");
          client.print("Requests received: ");
          client.print(++reqCount);
          client.print("<br>\r\n");
          client.print("Analog input A0: ");
          client.print(analogRead(0));
          client.print("<br>\r\n");
          client.print("</html>\r\n");
          break;
        }
        if (c == '\n') {
          // you're starting a new line
          currentLineIsBlank = true;
        }
        else if (c != '\r') {
          // you've gotten a character on the current line
          currentLineIsBlank = false;
        }
      }
    }
    // give the web browser time to receive the data
    delay(10);

    // close the connection:
    client.stop();
    Serial.println("Client disconnected");
  }
}

void printWifiStatus()
{
  // print the SSID of the network you're attached to
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your WiFi shield's IP address
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);
  
  // print where to go in the browser
  Serial.println();
  Serial.print("To see this page in action, open a browser to http://");
  Serial.println(ip);
  Serial.println();
}`

I get the following error.

`Arduino:` 1.6.5 (Windows 7), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

WebServer.ino: In function 'void setup()':
WebServer:64: error: 'printWifiStatus' was not declared in this scope
'printWifiStatus' was not declared in this scope

`
Even though it is in the code.  So i then comment it out and get a compiling error...

Arduino: 1.6.5 (Windows 7), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

\\GAS1\RedirectedFolders\AndrewC\My Documents\Arduino\libraries\WiFiEsp-master\src\utility\EspDrv.cpp: In static member function 'static bool EspDrv::getNetmask(IPAddress&)':
\\GAS1\RedirectedFolders\AndrewC\My Documents\Arduino\libraries\WiFiEsp-master\src\utility\EspDrv.cpp:516:8: error: 'class IPAddress' has no member named 'fromString'
   mask.fromString (buf);
        ^
\\GAS1\RedirectedFolders\AndrewC\My Documents\Arduino\libraries\WiFiEsp-master\src\utility\EspDrv.cpp: In static member function 'static bool EspDrv::getGateway(IPAddress&)':
\\GAS1\RedirectedFolders\AndrewC\My Documents\Arduino\libraries\WiFiEsp-master\src\utility\EspDrv.cpp:530:6: error: 'class IPAddress' has no member named 'fromString'
   gw.fromString (buf);
      ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

Any ideas?

**Comment by bportaluri** [comment]
Please update IDE to latest version (1.6.9) and retry.

**Comment by acremers87** [comment]
I have updated my IDE and this solved the issue. Thank you.
