### ISSUE TITLE
ESP hangs on Timeout

### ISSUE THREAD

**Issue by CycloneFire** [bportaluri/WiFiEsp#53]
At first here is the buggy code block - 

` WiFiEspClient client = myserver.available(); 
  if (client)
    {Serial.println("Incoming connection...");
    String readString = "";
    char c;

```
 boolean currentLineIsBlank = true;
```

  while(client.connected() )//&& millis()>(clienttimerecall+5000))
  {if(client.available()){ 
    c=client.read(); 
    readString+=c;

   if ((c == '\n' && currentLineIsBlank)){

 k = statefinder(readString);  ////////THIS BLOCK IS ENTIRELY WORK BASED
String printz="";                     //////// AND DOES NOT USE ANY ESP BASED
worker(k,readString);            //////// FUNCTIONS OR CALLS!
printz= clientprinter(k);          ///////

Serial.print("                         What came is this = ");
Serial.println(readString);
Serial.print("What I sent is this = ");
Serial.println(printz);

client.print("HTTP/1.1 200 OK\r\n");
client.print("\r\n");
client.print(printz);
client.print("\r\n");
break;}
if (c == '\n') {  currentLineIsBlank = true;
        }
        else if (c != '\r') {
          currentLineIsBlank = false;}

  }}delay(10);
client.stop();
Serial.println("Client disconnected");
`

Now the problem starts when i actually use the server,it works fine for some times but later esp hangs & thts how it goes-

`[WiFiEsp] New client 0
Incoming connection...
THE TEMPERATURE CHECKER SAYS = 33
Registered Time is = 0
Millis Time is = 57579
Start Time is = 0
                         What came is this = GET /LIGHT HTTP/1.1
Host: 192.168.0.49
Connection: Keep-Alive
User-Agent: Apache-HttpClient/UNAVAILABLE (java 1.4)

What I sent is this = light

> sendData: 0 17

OK

> Recv 17 bytes

SEND OK

> sendData: 0 2

OK

> Recv 2 bytes

SEND OK

> sendData: 0 5

OK

> Recv 5 bytes

SEND OK

> sendData: 0 2

OK

> Recv 2 bytes

SEND OK
[WiFiEsp] Disconnecting  0

> ## stopClient 0
> 
> > AT+CIPCLOSE=0
> > 0,CLOSED

OK
---------------------------------------------- > 0

Client disconnected

Data packet 0 121
[WiFiEsp] New client 0
Incoming connection...
[WiFiEsp] TIMEOUT: 102

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"z!â

Connected

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"z!â

Connected

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"z!â

Connected

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"z!â

Connected

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"z!â

Connected

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"z!â

Connected

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"z!â

Connected

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"z!â

Connected

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"z!â

Connected

|
|
|
|
|
|

//////That block keeps repeating until client is stopped & for reasons my client can't have timeouts//////
|
|
|
|
|
////and ends with this(when client is stopped

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > STATUS:3
> > +CIPSTATUS:0,"TCP","192.168.0.105",41324,1

OK
---------------------------------------------- > "TCP"B�

Connected

> ## getClientState 0
> 
> > AT+CIPSTATUS
> > 0,CLOSED
> > STATUS:4

OK
No start tag found: 0
---------------------------------------------- > 

Not connected
Client disconnected

`

As you can see i switched to debug mode of WifiESP & this problem doesn't seem to have any pattern ,it happens to any time without certain reasoning.....
The only thing that came up to me when i tried to dig up is that , two requests may be mixed up with each other & causing this...but i am not sure, could you please look up into this issue ,this issue is really pushing my project to my deadline & really causing me problems!!  
PLEASE HELP !!

**Comment by landscapejohn** [comment]
I'm running into basically the same problem. I'm just doing a simple GET to retrieve the value of the analog pins on the board and it works for the first several minutes but after 5 minutes or so it stops responding.

If I try to do a GET after that time has elapsed it logs a message to the serial monitor along the lines of the one you're seeing, i.e.:

STATUS:3
+CIPSTATUS:0,"TCP","10.0.1.7",41324,1

and then the browser just hangs waiting for a response from the server.

In my code I'm also logging the GET request to the serial monitor. I noticed that when this issue occurs that the first part of my GET request has been truncated, as if the board didn't receive it properly. However, once this occurs once all subsequent GETs fail even if they arrive to the board correctly.

**Comment by BeeSci** [comment]
I'm observing exactly the same behaviour while porting the Homeduino code on a Mega 2560 to support the ESP-01.
Has anybody/you found a solution yet? @CycloneFire ?
Could this be a timing issue? 
If I set the comm rate to 76800baud and #define _ESPLOGLEVEL_ 4 in debug.h the problem occurs at about 1 out of 25 tries. 
Same rate and ESPLOGLEVEL_2: 1 error in 12 tries. 
At 115200baud about 1 out of 10. 
Using 250000baud it occurs all the time: 0 out of x succeeds.

**Comment by BeeSci** [comment]
This is caused by a serial RX buffer overrun in the while(client.connected() loop.
If the buffer is not read fast enough the blankLine break criteria is missing and you are stuck within the loop. The client remains connected but doesn't deliver any data --> STATUS:3.
I solved it by increasing the serial RX buffer in HardwareSerial.h and speeding up the reading.

**Comment by CycloneFire** [comment]
I can't exactly test out your solution right now due to other project I m currently working on.... But the solution seems pretty solid and logical to me. Thanx very much for looking into it. I thought i should just go for some other library if it doesn't get solved, so you saved me a lot of trouble man! Thanks again.

**Comment by GreenEnergy1958** [comment]
Using a timer with millis in conjunction with "while (client.connected() )" seems to get around this issue.

while (client.connected() && currentTime - previousTime <= timeoutTime) {  
currentTime = millis(); 

I was already using the elapsedMillis library, so I shortened to this:

First add this before setup:
#include <elapsedMillis.h> 
elapsedMillis Timer1;

then:
while (client.connected() && Timer1 < 25000) {    // end 'while' loop after 25 seconds if there is a timeout
your code }                                                             // add your web server code here
Timer1 = 0;                                                             // reset Timer1 to 0

Found this solution here:
https://rntlab.com/question/solved-esp32-web-server-drops-connection-crashes/
