### ISSUE TITLE
Litle problem

### ISSUE THREAD

**Issue by telesyst** [bportaluri/WiFiEsp#6]
bool EspDrv::wifiConnect(char* ssid, const char *passphrase)
{
	INFO1(F("> wifiConnect"));
	
	bool ret;

	// connect to access point
	sprintf(cmdBuf, "AT+CWJAP=\"%s\",\"%s\"", ssid, passphrase);

	if (sendCmd(cmdBuf, 20000)==TAG_OK);    << Problem!  ; must not be here
	{
		return true;
	}
	
    return false;
}

**Comment by bportaluri** [comment]
Thank you I have already spotted that problem.
I have released a totally new version to use with new 1.1.1 SDK.
I hope you have a new module or you can flash it.
