### ISSUE TITLE
Can't declare member function to have static linkage

### ISSUE THREAD

**Issue by doffeDamon** [bportaluri/WiFiEsp#69]
Hi! I'm getting some errors trying to compile a sketch for arduino. Just by including <WiFiEsp.h> without any other code I'm getting these three errors and I can't figure out how to solve it. 
I appreciate any help I can get!

`/Users/Jesper/Documents/Documents/Arduino/libraries/WiFiEsp-master/src/WiFiEsp.cpp:209:44: error: cannot declare member function 'static uint8_t WiFiEspClass::getFreeSocket()' to have static linkage [-fpermissive]
 static uint8_t WiFiEspClass::getFreeSocket()
                                                                          ^
`

`
/Users/Jesper/Documents/Documents/Arduino/libraries/WiFiEsp-master/src/WiFiEsp.cpp:222:54: error: cannot declare member function 'static void WiFiEspClass::allocateSocket(uint8_t)' to have static linkage [-fpermissive]
 static void WiFiEspClass::allocateSocket(uint8_t sock)
                                                                                           ^
` 

`
/Users/Jesper/Documents/Documents/Arduino/libraries/WiFiEsp-master/src/WiFiEsp.cpp:227:53: error: cannot declare member function 'static void WiFiEspClass::releaseSocket(uint8_t)' to have static linkage [-fpermissive]
 static void WiFiEspClass::releaseSocket(uint8_t sock)
                                                                                          ^
`

**Comment by xsiriusx** [comment]
have same problem

**Comment by doffeDamon** [comment]
Try using the latest version of the Arduino IDE, worked for me

**Comment by JiriBilek** [comment]
Sorry, but this is an issue. See [http://stackoverflow.com/questions/8130066/static-member-functions-error-how-to-properly-write-the-signature](http://stackoverflow.com/questions/8130066/static-member-functions-error-how-to-properly-write-the-signature).
I am fixing it and will post a pull request.

**Comment by bportaluri** [comment]
Fix merged
