### ISSUE TITLE
Large GET request splits the data

### ISSUE THREAD

**Issue by WheresWally** [bportaluri/WiFiEsp#7]
I am reading read a page from my PV inverter.
I get all the web page source but only the first 1460 bytes can be read via client.read().
The next  3 blocks of 1460 bytes, 1270 bytes and 971 bytes are spat out as Trailing Data>>>>
How can I get all the GET to come back via client,read()  so I can parse it?

--------------------------------------------------------------------------------------------------------
>> AT+GMR
AT version:0.21.0.0
SDK version:0.9.5

OK
...  

SEND OK
> sendData: 0 1

OK
> 
SEND OK
New incoming connection - connId: 0
Bytes: 1460
HTTP/1.0 200 OK
Date: Sat, 19 Dec 2015 16:32:03 GMT
Server: Boa/0.94.13
Connection: close
Content-type:text/html;charset=utf-8

<html><head><meta http-equiv=pragma content=no-cache><meta http-equiv=expire content=now><title></title></head><body bgcolor=ffffff text=black><br><br><table align=center border=1 cellpadding=0 cellspacing=0 bordercolor=#008000 bordercolorlight=#ffffff borderdark=#808000 width=1024><center><tr bgcolor=#43CD80><td align=center>Inverter ID</td><td align=center>Current Power</td><td align=center>Grid Frequency</td><td align=center>Grid Voltage</td><td align=center>Temperature</td><td align=center>Date</td></tr></center><center><tr><td align=center>404000066544-A</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066544-B</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066570-A</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066570-B</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o<
>>> Trailing data >>>

+IPD,0,1460:sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066368-A</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066368-B</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066775-A</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066775-B</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066688-A</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066688-B</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066650-A</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><<<<<<<<<<<<<<<<<<<<<
/New incoming connection - connId: 0
Bytes: 1270
<td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066650-B</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066359-A</td><td align=center> 1&nbsp;W</td><td align=center> 49.9&nbsp;Hz</td><td align=center> 233&nbsp;V</td><td align=center> 31&nbsp;<sup>o</sup>C</td><td align=center> 2015-12-19 18:36:53</td></tr></center><center><tr><td align=center>404000066359-B</td><td align=center> 1&nbsp;W</td><td align=center> 49.9&nbsp;Hz</td><td align=center> 233&nbsp;V</td><td align=center> 31&nbsp;<sup>o</sup>C</td><td align=center> 2015-12-19 18:36:53</td></tr></center><center><tr><td align=center>404000066566-A</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066566-B</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066767-A</td><td align=c
>>> Trailing data >>>

+IPD,0,971:nter>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066767-B</td><td align=center>&nbsp;W</td><td align=center>&nbsp;Hz</td><td align=center>&nbsp;V</td><td align=center>&nbsp;<sup>o</sup>C</td><td align=center></td></tr></center><center><tr><td align=center>404000066774-A</td><td align=center> 2&nbsp;W</td><td align=center> 49.9&nbsp;Hz</td><td align=center> 234&nbsp;V</td><td align=center> 29&nbsp;<sup>o</sup>C</td><td align=center> 2015-12-19 18:36:53</td></tr></center><center><tr><td align=center>404000066774-B</td><td align=center> 2&nbsp;W</td><td align=center> 49.9&nbsp;Hz</td><td align=center> 234&nbsp;V</td><td align=center> 29&nbsp;<sup>o</sup>C</td><td align=center> 2015-12-19 18:36:53</td></tr></center></table><br><br><hr></hr><center><tr><td>&copy2013 Altenergy Power System Inc.</td></tr></center></body></html>0,CLOSED
<<<<<<<<<<<<<<<<<<<<<

**Comment by bportaluri** [comment]
Can you please share the sketch you are using?

**Comment by bportaluri** [comment]
I have made a fix.
Can you please download the latest version and tell me if it works?

**Comment by WheresWally** [comment]
YES !!! (sorry, the !!! might break something).
It does push all the incoming bytes through the client.read() now. 
Thanks

**Comment by WheresWally** [comment]
How can i send you a copy of my code securely.  I do not wish the code to be public, but i would like you to test it.It works sometimes, not every time.There are 20 micro inverters and it should display all 20 lines of data parsed from the HTML returned.Some times it stops after the 9th inverter.not sure why.Feel free to use the connection to my inverter, i have port-forwarded it so you can test it from there, where ever there is.As I am in Australia, the sun might not be shining when you test, but that will just give you 0W etc, should still be able to read the data.
email me simmicht at hotmail dot com if you like.Terry

Date: Sun, 20 Dec 2015 07:27:22 -0800
