### ISSUE TITLE
Cannot connect to WiFi router.

### ISSUE THREAD

**Issue by aharshac** [bportaluri/WiFiEsp#71]
I'm trying to connect to my home's wifi router in WebClient example. But it does not connect, giving timeout.

If I send AT command directly via FTDI to connect, it works.
```
AT+CWJAP="2015","<password>"
```

Here is my Serial Monitor output.
```
[WiFiEsp] Initializing ESP module
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Initilization successful - 1.3.0
Attempting to connect to WPA SSID: 2015
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Failed connecting to 2015
Attempting to connect to WPA SSID: 2015
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Failed connecting to 2015
Attempting to connect to WPA SSID: 2015
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Failed connecting to 2015
Attempting to connect to WPA SSID: 2015
```

**Comment by NitinSontakke** [comment]
Hello,

I am facing similar problem. If i upload the BareMinimum sketch to Arduino Uno and give AT commands all works good as described in article here.

However, when I am using any of the WiFiEsp sample sketches, i get following:

```
[WiFiEsp] Initializing ESP module
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] Cannot initialize ESP module
[WiFiEsp] >>> TIMEOUT >>>
[WiFiEsp] No tag found
WiFi shield not present
```

Any help would hugely appreciated.

**Comment by Wikibear** [comment]
Check your ESP baudrate! It's important that your firmware of ESP is not set to 115200 as standard. Then you get in trouble with Arduino. Arduino are not able to simulate high boudrates. 

My Solution for that:

1. Load debug example
2. Switch Baudrates to 9600 for serial console and 115200 for ESP
3. Try AT Commands on 9600 if you will get OK then your firmware is set to 115200 and this is not ok
4. Send AT Command: AT+UART=9600,8,1,0,0
5. Switch Baudrate to 115200 serial and 9600 for ESP

6. Use another example and try out

This cost me days over days... There are different firmware on chips and also baudrates. Take care that baudrates are not to high.

Hope this will help someone out there.

**Comment by NitinSontakke** [comment]
Thank you!

My only motive to take Arduino path (with ESP01 for WiFi) was nothing but more Analogue pins. However, after much of struggle I just dropped the whole idea and moved back to ESP8266 12E module and PCF8574. This is giving me more digital pins.

Thank you for reply nonetheless.

**Comment by mustafa-qamaruddin** [comment]
I am still having this issue, AT commands work splendidly well through Baud 115200 , but when I try to use WiFiESP.h it gives not able to initialize errors :( any ideas?

**Comment by mustafa-qamaruddin** [comment]
[WiFiEsp] Initializing ESP module
09:26:51.539 -> [WiFiEsp] >>> TIMEOUT >>>
09:26:53.550 -> [WiFiEsp] >>> TIMEOUT >>>
09:26:55.556 -> [WiFiEsp] >>> TIMEOUT >>>
09:26:57.561 -> [WiFiEsp] >>> TIMEOUT >>>
09:26:59.567 -> [WiFiEsp] >>> TIMEOUT >>>
09:27:00.553 -> [WiFiEsp] Cannot initialize ESP module
09:27:05.583 -> End Setup
09:27:06.568 -> [WiFiEsp] >>> TIMEOUT >>>
09:27:06.604 -> [WiFiEsp] No tag found
09:27:06.604 -> No WIFI Connection

**Comment by mustafa-qamaruddin** [comment]
I have tried this already: AT+UART=9600,8,1,0,0

**Comment by mustafa-qamaruddin** [comment]
```
#include <SoftwareSerial.h>
#include <WiFiEsp.h>
#include <WiFiEspClient.h>
#include <WiFiEspUdp.h>
#include <PubSubClient.h>

#define NETWORK_SSID      "Qamaruddin"
#define NETWORK_PASS      "abcd@1234"
#define ARB_SERVER      "192.168.43.25"
#define ARB_SERVERPORT  1883                   // use 8883 for SSL
#define ARB_USERNAME    ""
#define ARB_PW         ""
#define TOPIC "arduino/analog/A1"

SoftwareSerial esp8266Module(0, 1); // RX, TX
WiFiEspClient espClient;
PubSubClient client(espClient);
int value = 0;

void setup() 
{
    Serial.begin(57600);
    esp8266Module.begin(9600);

    pinMode(5, OUTPUT);
    pinMode(3, OUTPUT);
    pinMode(7, OUTPUT);
    // #1
    tone(3, 1000);
    digitalWrite(5, HIGH);
    digitalWrite(7, LOW);
    delay(1000);

    //#2
    noTone(3);
    digitalWrite(5, LOW);
    digitalWrite(7, HIGH);
    delay(1000);

    // #3
    tone(3, 1000);
    digitalWrite(5, HIGH);
    digitalWrite(7, LOW);
    delay(1000);

    // #4
    digitalWrite(5, LOW);
    digitalWrite(7, HIGH);
    noTone(3);

    // mqtt client
    client.setServer(ARB_SERVER, ARB_SERVERPORT);
    WiFi.init(&esp8266Module);
    Serial.println(F("End Setup"));
}


void loop() 
{
    digitalWrite(7, HIGH);

    if ( WiFi.status() != WL_CONNECTED ) {
      Serial.println(F("No WIFI Connection"));
      WiFi.begin(NETWORK_SSID, NETWORK_PASS);
      blink();
    }
    
    if (!client.connected()) {
      Serial.println(F("No MQTT Connection"));
      String clientId = "ESP8266Client-";
      clientId += String(random(0xffff), HEX);
      client.connect(clientId.c_str());
      blink();
    }

    ++value;
    client.publish(TOPIC, value);

    digitalWrite(7, LOW);
}

void blink() {
    digitalWrite(5, HIGH);
    delay(1000);
    digitalWrite(5, LOW);
    delay(1000);
}
```

**Comment by jandrassy** [comment]
what do you mean by "AT commands work at 115200"?

**Comment by zoomx** [comment]
Error here:
SoftwareSerial esp8266Module(0, 1); // RX, TX
Pin 0 and 1 are used by Serial, for softwareserial you must use another pins.
