### ISSUE TITLE
How to avoid hardcore SSID and Password ??

### ISSUE THREAD

**Issue by thanthdinesh** [bportaluri/WiFiEsp#76]
How to avoid hardcore SSID and Password ??

**Comment by adeschamps** [comment]
If you're using CMake, you could set something up using configure_file, where you `#define` your SSID and password with CMake variables. That would require a fair amount of setup though, and can lead to some obtuse compiler errors if you don't define the variables correctly.

Maybe a better way would be to just `#include "network_config.h"` or something similar. Then you put something like this in `network_config.h`:
```
// #define SSID "your ssid"
// #define PASSWORD "your password"
#if !defined SSID || !defined PASSWORD
#error "Please #define network settings in network_config.h"
#endif
```

**Comment by thanthdinesh** [comment]
Thank you for reply. I got solution we  use WPS functionality to get SSID and PASSWORD and eneble autoconnect esp8266.
