### ISSUE TITLE
MEGA compatibility

### ISSUE THREAD

**Issue by HButler63** [bportaluri/WiFiEsp#8]
The Arduino MEGA bootloader does not handle three exclamation marks in a row properly (it switches to monitoring mode) - which causes uploading any code using this library to fail. This can be easily solved by removing some of the "!" characters in EspDrv.cpp (lines 93 and 785).

I would consider this a bug in the MEGA bootloader, not in this library, but anyway it could solve many a headache!

**Comment by bportaluri** [comment]
Fixed. Thank you !!!
With 3 exclamation marks  :-)

**Comment by HButler63** [comment]
Sure, glad I could help!
        
        Thanks for sharing your library!
        
        Best regards, Hans.
        
      
    On 2015-12-20 13:43, Bruno wrote:
    
    
      Fixed. Thank you !!!
        With 3 exclamation marks :-)
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
      Geen virus
        gevonden in dit bericht.
        Gecontroleerd door AVG - www.avg.com
        Versie: 2016.0.7294 / Virusdatabase: 4489/11216 - datum van
        uitgifte: 12/20/15
