### ISSUE TITLE
Firmware needed

### ISSUE THREAD

**Issue by WheresWally** [bportaluri/WiFiEsp#9]
Hi, can anyone provide a link to firmware to update the ESP8622-01 the little blue one.
Currently AT+GMR returns 2.2.89.2, what ever that is.
I think WiFiERsp says ver 21.
I would like to upgrade to ver 22.

**Comment by WheresWally** [comment]
OK I was connected to something else...
This is what I actually see

AT+GMR
AT version:0.21.0.0
SDK version:0.9.5

**Comment by bportaluri** [comment]
Please take a look at this procedure: http://yaab-arduino.blogspot.it/2015/12/flashing-esp8266-firmware-arduino.html
I'm using Arduino Uno to flash the ESP but the procedure is similar.

**Comment by WheresWally** [comment]
Great doco, thanks. I do have a dead arduino that I can pop the chip out and see if the serial works.
I did try this with my FTDI at 5V to a 3V regulator and resistor voltage divider, works well in terminal terminal and all the AT commands worked on COM12 at 9600. Ver 21

I followed the like, using the same versions of flasher and BINs as described there.
BUT when I did the GPIO0 to GND, powered up and tried to flash it, nothing.
FAILED showed up and now I can not even get the Blue LED to light on that ESP8266-01 now.

SO I placed my 3rd unopened ESP8266 in my circuit and it does work fine as it should so I might not try upgrading and failing a 3rd time.
2 ESP8266's are now in the DEAD bucket ...

**Comment by bportaluri** [comment]
I also had a lot of problems trying to flash ESP with my FTDI board. I bricked at least two ESPs but I was able to reflash them using the Aurduino Uno as described in my post.
I think that there are a lot of unreliable FTDI boards around...
Try flashing the broken modules using Arduino. Removing the chip from the Arduino board is non-destructive. I have done it more than 30 times during my experiments.

**Comment by WheresWally** [comment]
I pulled out the old UNO board from the DEAD STUFF box. I removed the chip.
Hooked up the ESP8622 and Blue LED lights, and flickes when i send data to the ESP but nothing comes back from it, and that makes me think, that was the reason the board was declared dead 3 years ago.
It is a one-way serial port, so that isn't going to work. 
Return to drawing board. I have soem new ESP8266-01 on order and i have also ordered a CP2102 USB To TTL/Serial Module UART STC Downloader For Arduino for $3 from Banggood so that might work.

**Comment by WheresWally** [comment]
Grabbed another UNO board, this ine has the chip surface mount so i cant remove it, BUT i have soldered a jumper across the reset button to keep the ATMEL chip in reset mode.
And I can now do AT commands to the ESP8266 and it responds correctly.

Ran the FLASH downloader and it seems to grab the setting from the ESP8266 but i do not get a progress bar and nothing downloads it seems 
See picture.
![flasher fails](https://cloud.githubusercontent.com/assets/16352494/12069824/4752ac90-b09b-11e5-90b8-052e343b8e74.png)

**Comment by WheresWally** [comment]
OK, I do need to check the box beside the file to download ... or else nothing.

**Comment by WheresWally** [comment]
If I do only one file at a time, I can do the blank.bin ok
the other 2 fail.
![flasher fails at 10 percent](https://cloud.githubusercontent.com/assets/16352494/12070104/d527ace6-b0aa-11e5-95f5-44623aed7bdf.png)

**Comment by bportaluri** [comment]
You haven't set the flash size to 8Mbit.
Raise the baud rate to 115200. This is not related to the default baud rate of the ESP module.
Sometimes also the order of bin files matters. See screenshot.
You can select the 4 bins and flash them in one shot. It should work.
![flash_1 5_ok](https://cloud.githubusercontent.com/assets/4365993/12070503/b6b996fc-b078-11e5-8f24-4df4009fac34.png)

**Comment by WheresWally** [comment]
I have tried both so those 3 suggestions and still it stops at xxxxC00. only 3K into any file.
Sorry to be such a pain.

**Comment by bportaluri** [comment]
I understand your pain. I also had many problems before but now I have a reliable process. I believe ESP is very sensitive to FTDI device and wiring. Use a reliable 3.3V power source and good UART.
I have no more suggestions...
Sorry

**Comment by WheresWally** [comment]
A large decoupling cap allowed it to work once.
So now i have one done at 1.5

**Comment by bportaluri** [comment]
Great!
Where did you put the the capacitor and how big it is?
We are all learning here...

**Comment by WheresWally** [comment]
10iF right before the regulator, only worked for 1 of the 3 dead ESP8266-01,
i tried also putting the 10uF across the ESP directly but still no flashing.
i should have looked closer to see if the blank,bin would flash.

**Comment by WheresWally** [comment]
The other 2 are now alive. I now have 3 working ESP8266 at 1.5 version level.
This uses a cheapie Arduino UNO and the RESET to GND trick to allow the board to act as a serial interface.
I made another ESP8266 programmer, I have a small PCB that has the 5V to 3V regulator a capacitor or 2 and the resistor divider. the surface mount is a little tricky to hand solder but with some strong glasses and revers tweezers to hold the part, it is easy enough.

Here is the setup in pictures.
![p1270035](https://cloud.githubusercontent.com/assets/16352494/12073255/36dc1844-b161-11e5-9eb2-fe5d01d397f5.JPG)
![p1270036](https://cloud.githubusercontent.com/assets/16352494/12073258/3c45887e-b161-11e5-9bd9-cd4166355606.JPG)
![p1270037](https://cloud.githubusercontent.com/assets/16352494/12073259/40deeff6-b161-11e5-83ac-5ddeb661caef.JPG)
![p1270039](https://cloud.githubusercontent.com/assets/16352494/12073260/48006878-b161-11e5-87e5-0d82908fad39.JPG)

![esp8266_top](https://cloud.githubusercontent.com/assets/16352494/12073262/4e5af3e6-b161-11e5-8a68-16f5710a1850.png)
![esp8266_bot](https://cloud.githubusercontent.com/assets/16352494/12073263/53a19a08-b161-11e5-8325-0854422d5f21.png)

**Comment by WheresWally** [comment]
I found that the size needs to be set to 4M for my hardware, when it was set to 8M after one or two RST commands it would go all screwy, spit out characters that were random.
The Flash Downloader does say under detected Info for my device, that the flash is 4Mb.
When I re-flashed at 4M the EPS8266 is now stable after about 20 resets.
I repeated this on 2 devices, same.

**Comment by bportaluri** [comment]
Thank you for sharing. I will use your tips for a 'troubleshooting guide for flashing ESP firmware'.
